INSERT INTO `product`(`id`, `category_id`, `name`, `description`, `price`, `image`, `status`, `added_on`) VALUES
(1, 1, 'man1', 'men's clothing', 9.99, '/images/men/men-blacktee.jpg', 1, NOW()),
(2, 1, 'man2', 'men's clothing', 19.99, '/images/men/men-blazer.jpg', 1, NOW()),
(3, 1, 'man3', 'men's clothing', 29.99, '/images/men/men-jeans-jacket.jpg', 1, NOW()),
(4, 1, 'man4', 'men's clothing', 39.99, '/images/men/men-lacoste.jpg', 1, NOW()),
(5, 1, 'man5', 'men's clothing', 49.99, '/images/men/men-sports.jpg', 1, NOW()),
(6, 1, 'man6', 'men's clothing', 59.99, '/images/men/men-whitetee.jpg', 1, NOW()),
(7, 2, 'woman1', 'women's clothing', 69.99, '/images/women/women-casual.jpg', 1, NOW()),
(8, 2, 'woman2', 'women's clothing', 79.99, '/images/women/women-decent.jpg', 1, NOW()),
(9, 2, 'woman3', 'women's clothing', 89.99, '/images/women/women-jacket.jpg', 1, NOW()),
(10, 2, 'woman4', 'women's clothing', 99.99, '/images/women/women-shirt.jpg', 1, NOW()),
(11, 2, 'woman5', 'women's clothing', 59.99, '/images/women/women-sports.jpg', 1, NOW()),
(12, 2, 'woman6', 'women's clothing', 19.99, '/images/women/women-suit.jpg', 1, NOW()),
(13, 3, 'boy1', 'boy's clothing', 29.99, '/images/boy/boys-beach.jpg', 1, NOW()),
(14, 3, 'boy2', 'boy's clothing', 39.99, '/images/boy/boys-traditional.jpg', 1, NOW()),
(15, 3, 'boy3', 'boy's clothing', 49.99, '/images/boy/boys-gentle.jpg', 1, NOW()),
(16, 3, 'boy4', 'boy's clothing', 59.99, '/images/boy/boys-indian.jpg', 1, NOW()),
(17, 3, 'boy5', 'boy's clothing', 69.99, '/images/boy/boys-sports.jpg', 1, NOW()),
(18, 3, 'boy6', 'boy's clothing', 79.99, '/images/boy/boys-whitetee.jpg', 1, NOW()),
(19, 4, 'girl1', 'girl's clothing', 89.99, '/images/girl/girl-carwash.jpg', 1, NOW()),
(20, 4, 'girl2', 'girl's clothing', 99.99, '/images/girl/girl-chinese.jpg', 1, NOW()),
(21, 4, 'girl3', 'girl's clothing', 09.99, '/images/girl/girl-cook.jpg', 1, NOW()),
(22, 4, 'girl4', 'girl's clothing', 19.99, '/images/girl/girl-fullydressed.jpg', 1, NOW()),
(23, 4, 'girl5', 'girl's clothing', 29.99, '/images/girl/girl-traditional.jpg', 1, NOW()),
(24, 4, 'girl6', 'girl's clothing', 39.99, '/images/girl/girl-whitegown.jpg', 1, NOW()),
(25, 5, 'baby1', 'baby's clothing', 49.99, '/images/baby/baby1.jpg', 1, NOW()),
(26, 5, 'baby2', 'baby's clothing', 59.99, '/images/baby/baby2.jpg', 1, NOW()),
(27, 5, 'baby3', 'baby's clothing', 69.99, '/images/baby/baby3.jpg', 1, NOW()),
(28, 5, 'baby4', 'baby's clothing', 79.99, '/images/baby/baby4.jpg', 1, NOW()),
(29, 5, 'baby5', 'baby's clothing', 89.99, '/images/baby/baby5.jpg', 1, NOW()),
(30, 5, 'baby6', 'baby's clothing', 99.99, '/images/baby/baby6.jpg', 1, NOW()),
(31, 6, 'accessory1', 'accessories', 39.99, '/images/accessory/accessory-bag.jpg', 1, NOW()),
(32, 6, 'accessory2', 'accessories', 19.99, '/images/accessory/accessory-chain.jpg', 1, NOW()),
(33, 6, 'accessory3', 'accessories', 29.99, '/images/accessory/accessory-necklace-three.jpg', 1, NOW()),
(34, 6, 'accessory4', 'accessories', 39.99, '/images/accessory/accessory-necklace.jpg', 1, NOW()),
(35, 6, 'accessory5', 'accessories', 49.99, '/images/accessory/accessory-rings-two.jpg', 1, NOW()),
(36, 6, 'accessory6', 'accessories', 59.99, '/images/accessory/accessory-rings.jpg', 1, NOW()),
(37, 6, 'accessory7', 'accessories', 69.99, '/images/accessory/accessory-watch.jpg', 1, NOW()),
(38, 6, 'accessory8', 'accessories', 79.99, '/images/accessory/accessory-shoe.jpg', 1, NOW());